TMP_DIR=./tmp

TMP_VER=$(TMP_DIR)/version_num.tmp

.PHONY: bin version

all: bdist

version:
	test -d $(TMP_DIR) || mkdir $(TMP_DIR)
	git describe | sed s/-/_/g > $(TMP_VER)

bdist: version
	rm -f ./memcached_*.tar.gz
	rm -rf $(TMP_DIR)/memcached
	mkdir $(TMP_DIR)/memcached
	cp memcached $(TMP_DIR)/memcached
	cp .libs/default_engine.so $(TMP_DIR)/memcached
	tar --directory $(TMP_DIR) -czf memcached_`cat $(TMP_VER)`.tar.gz memcached
	echo created memcached_`cat $(TMP_VER)`.tar.gz

